/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.andihasan7.lib.irsyadulmurid

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
